version: "3.9"
services:
  nginx-example:
    image: nginx:alpine
    container_name: nginx-example
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: false
      
      - type: bind
        source: ./default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: false
      - ./static_pages/:/usr/share/nginx/html/
    restart: always
    depends_on:
      - demo-api
    networks:
      - demo-network
  
  demo-api:
    image: vad1mo/hello-world-rest
    container_name: demo-api
    ports:
      - "5050:5050"
    networks:
    - demo-network
networks:
   demo-network:
    name: demo-network